// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQuzmTcuHNQrMmsOzkD143J5YX6FIfvIc',
    appId: '1:1017346159206:web:d1b214e67bcd63f471f3a7',
    messagingSenderId: '1017346159206',
    projectId: 'quizzapp-275a7',
    authDomain: 'quizzapp-275a7.firebaseapp.com',
    storageBucket: 'quizzapp-275a7.appspot.com',
    measurementId: 'G-Z1G7NDWRY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBezXCYhHyfUocX46A2tnOkTM8J5njhQq8',
    appId: '1:1017346159206:android:7aefa0a9858491ed71f3a7',
    messagingSenderId: '1017346159206',
    projectId: 'quizzapp-275a7',
    storageBucket: 'quizzapp-275a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASrOOpGUtQAkLYLdI0PtebQ49eW4DvcKM',
    appId: '1:1017346159206:ios:00e7394589bd4f4471f3a7',
    messagingSenderId: '1017346159206',
    projectId: 'quizzapp-275a7',
    storageBucket: 'quizzapp-275a7.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASrOOpGUtQAkLYLdI0PtebQ49eW4DvcKM',
    appId: '1:1017346159206:ios:4ab0dc979cb03fe271f3a7',
    messagingSenderId: '1017346159206',
    projectId: 'quizzapp-275a7',
    storageBucket: 'quizzapp-275a7.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
